version: '3.3'

services:
    adminer:
        image: adminer:latest
        labels:
          - traefik.enable=true
          - traefik.http.routers.net-ouiedire-data-adminer.rule=Host(`adminer.net.ouiedire.data.localhost`)
          - traefik.http.routers.net-ouiedire-data-adminer.entrypoints=web
    
    traefik:
        command:
        - --api=true
        - --api.dashboard=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        env_file: .env
        image: traefik:v2.2.8
        labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.http.routers.net-ouiedire-data-traefik.rule=Host(`traefik.net.ouiedire.data.localhost`)
        - traefik.http.routers.net-ouiedire-data-traefik.service=api@internal
        ports:
        - 80:80
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

    portainer:
        image: portainer/portainer:1.24.1-alpine
        labels:
            - traefik.enable=true
            - traefik.http.routers.net-ouiedire-data-portainer.rule=Host(`portainer.net.ouiedire.data.localhost`)
            - traefik.http.routers.net-ouiedire-data-portainer.entrypoints=web
            - traefik.http.services.net-ouiedire-data-portainer.loadbalancer.server.port=9000